theme: jekyll-theme-midnight
description: Reaticulate | a free articulation management system for REAPER
breadcrumbs: true
markdown: CommonMarkGhPages
commonmark:
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
kramdown:
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    line_numbers: false
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
